### PR TITLE
EX-3551 fixes isSearch

### PR DESCRIPTION
**Pull request by luciancor**
@past we have an update for one of our telemetry signals

cc @dominiks-cliqz

### CODE REVIEW

**Comment by past** [comment]
Looks fine to me. Is this test-pilot only?

**Comment by dominiks-cliqz** [comment]
@past it's for all platforms.

**Comment by luciancor** [comment]
We cherry-picked this one from our master. It will land in all our next versions with the next releases.

**Comment by past** [comment]
OK, makes sense. Thanks!

**Pull request merged**
