### PR TITLE
EX-3556: fix autocomplete popup in Nightly (FF52+)

### PR DESCRIPTION
**Pull request by luciancor**
Finally found a fix for this issue!

@past can you please take a look :)

### CODE REVIEW

**Comment by past** [comment]
Oh, I think this is what @mak77 was suspecting as well. I'll defer to him.

**Comment by luciancor** [comment]
Tested it in a few versions of FF and everything seems fine. It also cleans on disable so we could go with this fix.
Somehow it doesn't feel right though. Maybe there is a better solution.

**Comment by past** [comment]
Sure, we can go with this fix. I just want to give Marco a chance to confirm if [this](https://hg.mozilla.org/mozilla-central/rev/9fb7792946fb) change was the cause of breakage.

**Comment by mak77** [comment]
Sorry, I'm in the middle of re-download and re-installing the compiler due to a corrupt fs. If everything goes well I should be able to have confirmation and eventually an upstream fix tomorrow. I suspect the problem is that the popup property is initialized at a different time than before, but I need to confirm the behavioral change between the old field and the new property to be 100% sure what is happening there. The fix that I pointed out (and Panos reported) was indeed pushed to FF52, and it is just one day after the regression range found by mozregression. Supposing some skew there and the fix here, it looks very likely to be the problem.

**Comment by mak77** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1323600

**Comment by past** [comment]
Thanks Marco! We should take this workaround now, but should consider removing it once uplifts are done.

**Comment by luciancor** [comment]
thanks guys!

**Pull request merged**
